[package]
name = "empower-studio"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
empower-engine = { path = "../empower-engine" }
empower-node-graph = { path = "../empower-node-graph" }
eframe = "0.31"
# eframe = { git = "https://github.com/Stretchyfish/egui.git", package = "eframe", branch = "feature/scene_mouse_position" }
egui = "0.31"
# egui = { git = "https://github.com/Stretchyfish/egui.git", branch = "feature/scene_mouse_position" }
egui_dock = "0.16"
